language: node_js

node_js:
  - '0.12'
  - '0.10'

sudo: false

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate < coverage/lcov.info

addons:
  code_climate:
    repo_token: xxx
